CREATE DATABASE IF NOT EXISTS kaze_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kaze_db;

CREATE TABLE IF NOT EXISTS admins (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS berita (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    judul VARCHAR(180) NOT NULL,
    kategori ENUM('Klub', 'Latihan', 'Turnamen') NOT NULL DEFAULT 'Klub',
    isi TEXT NOT NULL,
    tanggal DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pemain (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(120) NOT NULL,
    posisi ENUM('Tunggal', 'Ganda') NOT NULL DEFAULT 'Tunggal',
    nickname VARCHAR(80) NOT NULL,
    foto VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS turnamen (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(160) NOT NULL,
    tanggal DATE NOT NULL,
    lokasi VARCHAR(160) NOT NULL,
    status ENUM('Akan Datang', 'Berlangsung', 'Selesai') NOT NULL DEFAULT 'Akan Datang',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS score (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pemain_id INT UNSIGNED NOT NULL,
    turnamen_id INT UNSIGNED NOT NULL,
    point SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    tanggal DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_score_pemain FOREIGN KEY (pemain_id) REFERENCES pemain(id) ON DELETE CASCADE,
    CONSTRAINT fk_score_turnamen FOREIGN KEY (turnamen_id) REFERENCES turnamen(id) ON DELETE CASCADE
);

